# Generated by Django 2.2.5 on 2019-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('tecnico_infcam', 'Fornece acesso de técnico da Infcam'),), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
