# Generated by Django 2.1.3 on 2018-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('db', models.CharField(max_length=100, verbose_name='Banco de Dados')),
                ('username', models.CharField(max_length=100, verbose_name='Banco de Dados')),
                ('uid', models.IntegerField(verbose_name='ID de Usuário')),
                ('password', models.CharField(max_length=100, verbose_name='Banco de Dados')),
            ],
            options={
                'verbose_name': 'Odoo',
                'verbose_name_plural': 'Odoo',
                'ordering': ['url'],
            },
        ),
    ]
