# Generated by Django 2.1.3 on 2018-12-18 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odoo', '0003_odoouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooParceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='odoouser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='odoouser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='OdooUser',
        ),
    ]
