# Generated by Django 2.1.3 on 2018-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0004_auto_20181218_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odooparceiro',
            options={'verbose_name': 'Parceiro Odoo', 'verbose_name_plural': 'Parceiros Odoo'},
        ),
        migrations.AddField(
            model_name='odooparceiro',
            name='id_parceiro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
