# Generated by Django 2.1.3 on 2018-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0005_auto_20181218_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooparceiro',
            name='tipo_cliente',
            field=models.CharField(choices=[('BL', 'Banda Larga'), ('CORP', 'Corporativo'), ('LIC', 'Licitado')], default='BL', max_length=3, verbose_name='Tipo do Cliente'),
        ),
    ]
