# Generated by Django 2.2.5 on 2019-09-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0007_auto_20181220_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odooparceiro',
            name='tipo_cliente',
        ),
    ]
